### ISSUE TITLE
Delays on Jericho Player Development | Spotify API Request

### ISSUE THREAD

**Issue by kabirsingh2004** [SidisLiveYT/Video-Extractor#8]
How to Get jericho-player Package please publish it

**Comment by SidisLiveYT** [comment]
> How to Get jericho-player Package please publish it

I will do it , I am adding some more features . you can until then use package like - `npm i https://github.com/SidisLiveYT/Jericho-Player`
and to update or uninstall - `npm uninstall jericho-player` 

I need like 1 or 2 days more to complete the basic features

**Comment by kabirsingh2004** [comment]
Can You make this only spotify player so remove youtube api
if you need help regarding this contant me on discord 
Discord = Justin Bieber#9610

**Comment by SidisLiveYT** [comment]
> Can You make this only spotify player so remove youtube api if you need help regarding this contant me on discord Discord = Justin Bieber#9610

btw it supports all , And why I will make spotify only ? and if you want it as spotify player , you can just check query or urls with spotify regex and work on it

**Comment by SidisLiveYT** [comment]
Jericho Player has been Published and Updated ! you can install by - `npm i jericho-player@latest`
